export const TAPBACKS = ["❤️", "👍", "👎", "😂", "‼️", "❓"];

/** Curated set for the reaction picker: [emoji, search words]. */
export const EMOJI: [string, string][] = [
  ["😀", "grin happy smile"], ["😃", "smile happy"], ["😄", "laugh smile"], ["😁", "beam grin"], ["😆", "laugh squint"],
  ["🥹", "touched tears grateful"], ["😅", "sweat relief"], ["🤣", "rofl laugh"], ["😂", "joy laugh cry"], ["🙂", "slight smile"],
  ["🙃", "upside down silly"], ["😉", "wink"], ["😊", "blush happy"], ["😇", "angel innocent"], ["🥰", "love hearts"],
  ["😍", "heart eyes love"], ["🤩", "star struck wow"], ["😘", "kiss"], ["😋", "yum tasty"], ["😛", "tongue"],
  ["😜", "wink tongue crazy"], ["🤪", "zany crazy"], ["🤓", "nerd glasses"], ["😎", "cool sunglasses"], ["🥳", "party celebrate"],
  ["😏", "smirk"], ["😌", "relieved calm"], ["😴", "sleep tired"], ["🤤", "drool"], ["😪", "sleepy"],
  ["🤔", "thinking hmm"], ["🫡", "salute"], ["🤗", "hug"], ["🤭", "giggle oops"], ["🫢", "gasp"],
  ["🤫", "shush quiet"], ["🙄", "eye roll"], ["😬", "grimace awkward"], ["😮‍💨", "exhale phew"], ["🤥", "lie"],
  ["😐", "neutral"], ["😑", "expressionless"], ["😶", "speechless"], ["🫠", "melt"], ["😳", "flushed embarrassed"],
  ["🥺", "pleading please"], ["😢", "cry sad"], ["😭", "sob crying"], ["😤", "huff triumph"], ["😠", "angry"],
  ["😡", "rage mad"], ["🤯", "mind blown"], ["😱", "scream shock"], ["😨", "fear"], ["🥶", "cold freezing"],
  ["🥵", "hot"], ["🤢", "sick nausea"], ["🤒", "ill thermometer"], ["🤧", "sneeze"], ["😷", "mask"],
  ["🤠", "cowboy"], ["🤡", "clown"], ["👻", "ghost boo"], ["💀", "skull dead"], ["👽", "alien"],
  ["🤖", "robot"], ["💩", "poop"], ["😺", "cat smile"], ["🙈", "see no evil monkey"], ["🙊", "speak no evil"],
  ["👍", "thumbs up yes like"], ["👎", "thumbs down no"], ["👏", "clap applause"], ["🙌", "raise hands hooray"], ["🙏", "pray thanks please"],
  ["🤝", "handshake deal"], ["👋", "wave hello bye"], ["✌️", "peace victory"], ["🤞", "fingers crossed luck"], ["🤌", "pinched italian"],
  ["👌", "ok perfect"], ["🫶", "heart hands"], ["💪", "strong flex muscle"], ["👀", "eyes look"], ["🧠", "brain smart"],
  ["❤️", "red heart love"], ["🧡", "orange heart"], ["💛", "yellow heart"], ["💚", "green heart"], ["💙", "blue heart"],
  ["💜", "purple heart"], ["🖤", "black heart"], ["🤍", "white heart"], ["💔", "broken heart"], ["💖", "sparkling heart"],
  ["💯", "hundred perfect"], ["‼️", "exclamation emphasis"], ["❓", "question"], ["✅", "check done yes"], ["❌", "cross no"],
  ["⚠️", "warning"], ["🔥", "fire lit hot"], ["✨", "sparkles magic"], ["⭐", "star"], ["🌟", "glowing star"],
  ["⚡", "lightning zap"], ["💥", "boom"], ["💫", "dizzy"], ["🎉", "tada party"], ["🎊", "confetti"],
  ["🎈", "balloon"], ["🎁", "gift present"], ["🏆", "trophy win"], ["🥇", "gold medal first"], ["🎯", "target bullseye"],
  ["☀️", "sun sunny"], ["🌤", "sun cloud"], ["🌧", "rain"], ["❄️", "snow"], ["🌈", "rainbow"],
  ["🌙", "moon night"], ["🌊", "wave ocean"], ["🌱", "sprout plant grow"], ["🌸", "blossom flower"], ["🍀", "clover luck"],
  ["☕", "coffee"], ["🍵", "tea"], ["🍕", "pizza"], ["🍜", "ramen noodles"], ["🍣", "sushi"],
  ["🌮", "taco"], ["🥐", "croissant"], ["🍞", "bread sourdough"], ["🍰", "cake"], ["🍷", "wine"],
  ["🍺", "beer"], ["🥂", "cheers toast"], ["🏃", "run running"], ["🚴", "bike cycling"], ["🧘", "yoga calm"],
  ["✈️", "plane travel flight"], ["🚗", "car drive"], ["🏠", "home house"], ["💼", "work briefcase"], ["💻", "laptop computer"],
  ["📱", "phone"], ["📅", "calendar date"], ["⏰", "alarm clock"], ["📚", "books read"], ["✏️", "pencil write"],
  ["📝", "memo note"], ["📌", "pin"], ["🔒", "lock secure"], ["💡", "idea bulb"], ["🔔", "bell notification"],
  ["💰", "money bag"], ["💸", "money spend"], ["🛒", "cart shopping"], ["🐶", "dog puppy"], ["🐱", "cat kitty"],
  ["🦊", "fox"], ["🐻", "bear"], ["🐼", "panda"], ["🐸", "frog"], ["🦄", "unicorn"],
];
